### ISSUE TITLE
Manager | Enroll Students in a Course and Monitoring Training Compliance

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#10]
Training Manager | Enroll Students in a Course (Suggestion)

This screen directs them to the Manager role, but I don’t believe that the Manager role is widely available to TMs. I’m not sure that most TMs have the ability to enroll learners into courses or even view that dashboard at the top of the page.  

Training Manager | Monitoring Training Compliance (Suggestion)

This screen directs them to the Manager role, but I don’t believe that the Manager role is 
widely available to TMs.

Consider adding a note to the bottom of both screens which states something like, "*For eligible Manager designees. This is not widely available to Training Managers at this time."

**Comment by artlessdodger** [comment]
Patched in the next release. An asterisk providing information to this effect has been added in the introduction to these two pages.

See commit [6636ef8](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/6636ef824f6cdf1a7ceb98fce4fd91343283748c) for details.
