### ISSUE TITLE
Administrator | Create and Subscribe Dashboard Reports

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#11]
Suggested new entry for the Admin page on how to add a dashboard report and how to subscribe. 

These should run each morning at about 1AM, and will be sent to your email inbox. These dashboard reports can be customized to suit your needs. 

From the Reports page, select Custom Reports, then hit the tab for Dashboard Reports. Hit the button Add Dashboard.

![image](https://user-images.githubusercontent.com/73358235/118872763-2d5bb980-b8a6-11eb-9477-df520f5f466b.png)

You will be prompted to add a name. You may also add a description, and it may be shared with other users who have Administrator and Manager access in Prime. Hit Save.

![image](https://user-images.githubusercontent.com/73358235/118872804-36e52180-b8a6-11eb-85cb-ae7ffb77e2c0.png)

The Dashboard will then show up in the middle of the page. Select Add Report.

![image](https://user-images.githubusercontent.com/73358235/118872832-3f3d5c80-b8a6-11eb-85d2-c6ef72b58961.png)

Your selections should match this screen, though you will want to name your report. 

![image](https://user-images.githubusercontent.com/73358235/118872867-49f7f180-b8a6-11eb-8498-c510f610bca1.png)

For Time Span, you will select the value you want. 

![image](https://user-images.githubusercontent.com/73358235/118872895-5419f000-b8a6-11eb-87f4-6620ceafd493.png)

Under Filters, you will hit the Content tab, then select Catalogs, and enter the catalogs you wish to run. For example, our normal reports are the FY21 Required Trainings, MST Specialized Processors, and ALS Specialized Processors. 

![image](https://user-images.githubusercontent.com/73358235/118872945-609e4880-b8a6-11eb-83b7-a5e9d885df9d.png)

Last, you will select Show data for current values, then hit Save.

![image](https://user-images.githubusercontent.com/73358235/118872979-6d22a100-b8a6-11eb-8eed-2291d821bb6d.png)

To receive daily emails, select the Subscriptions tab at the top. Type in your report name, select frequency, you may customize your subject, and you can add an alternate email in the event that you have a backup. Check the box Include Transcript to receive the Excel spreadsheet. Hit the checkmark.

Note that you will not receive a report until the following day. In the interim, you may instead run a Learner Transcript report.

![image](https://user-images.githubusercontent.com/73358235/118873003-77dd3600-b8a6-11eb-870a-fbad569c0631.png)

**Comment by artlessdodger** [comment]
Patched in the next release. A subpage has been created to address this task.

See commit [2fe3b3c](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/2fe3b3c42920419ddc4dce08bd29d3badea3f453) for details.
