### ISSUE TITLE
Learner | My Learning and Catalogs

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#12]
Suggested addition to the Learner Page (because some people don't even try this and can't see their courses sometimes).

From the Home screen, click on My Learning from the left menu.

![image](https://user-images.githubusercontent.com/73358235/118876919-0a7fd400-b8ab-11eb-9e71-6077a5838e59.png)

On the left, you can refine your search by Catalog, Type, and/or Status. 

![image](https://user-images.githubusercontent.com/73358235/118877008-2a16fc80-b8ab-11eb-83a0-92f26e668b31.png)

From the left menu, select the 6 boxes to go to the Catalog page. 

![image](https://user-images.githubusercontent.com/73358235/118877409-a6114480-b8ab-11eb-965f-72b8f6bf8576.png)

Once on the Catalog page, you can filter your content based on Catalog, Type, and/or Status. 

![image](https://user-images.githubusercontent.com/73358235/118877508-c2ad7c80-b8ab-11eb-886f-16c18e3fba1e.png)

**Comment by artlessdodger** [comment]
Patched in the next release. A new page has been created to meet this need.

See commit [3fe2959](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/3fe2959c1919073c4174fda3ae2df35bd0ecf0e0) for details.
