### ISSUE TITLE
Administrator | Marking a User's Progress Complete

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#13]
Administrator | Marking a User's Progress Complete (Suggestion)

Consider adding onto this page how to reset the module for the user since the processes are almost identical.

To reset the module for a user, search for the user by name or VA email address. Select the user, then select Reset Modules under Actions drop-down. 

![image](https://user-images.githubusercontent.com/73358235/118878954-65b2c600-b8ad-11eb-92b0-6e3b23b10c34.png)

**Comment by artlessdodger** [comment]
Patched in next release. 

This page has been changed to "Administrator | Change a User's Progress Status" to include guidance on both marking completions and resetting modules. See commit [03d96d4](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/03d96d43c5e60983c6711439564f4d3bde01596f) for details.
