### ISSUE TITLE
Autoplay JavaScript replacement for Captivate modules

### ISSUE THREAD

**Issue by aricdostal** [compensationServiceTraining/primeTechnicalManual#14]
Create a section in the PTM for content publishers to replace the Autoplay JavaScript for Captivate modules.

**Comment by artlessdodger** [comment]
Patched in the next release. A subpage in the publisher role has been created to serve this purpose. 

See commit [cc89081](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/cc890810256a3c6ef970afc346649255f9aead09) for details.
