### ISSUE TITLE
Training Manager | Enroll Students

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#19]
Request from Adobe Prime TM Workgroup:

Add a note in this segment of the User Guide explaining that learners should not be enrolled in the IC courses and only the student courses without the IC designation.

**Comment by artlessdodger** [comment]
Added to the mentioned page — see commit [c9a84c4
](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/c9a84c405883c45159aef9005e33eaae0dcbce70).

Will be published in the next release.
