### ISSUE TITLE
Index | Link to Prime Login

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#25]
The TMP mailbox receives multiple inquiries (especially with the assignment of mandatory courses) by users who have active Prime accounts, but don't know how to actually access it. I propose that we provide a login page hyperlink on the main page of the Prime Technical Manual (highlighted recommended places to put links).

![image](https://user-images.githubusercontent.com/73358235/133338429-c320ee94-1aba-4bd5-8dab-0e93759f70ca.png)

**Comment by artlessdodger** [comment]
Added a button to the index — see commit [466fcce
](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/466fcce334b5c934bfbb02e05a51a46b5c80c10f) 

Will be published in the next release.
