### ISSUE TITLE
Learner | Download Resources Hyperlink Issue 

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#3]
Learner > Download Course Resources
	Text Version: Hyperlink “enrolling in a course” is not functioning (image below). Please update link.

![image](https://user-images.githubusercontent.com/73358235/118866280-0ea5f480-b89f-11eb-8db3-e9b3eca67a80.png)

**Comment by artlessdodger** [comment]
Patched in next release.
