### ISSUE TITLE
Learner | Choose a Compatible Web Browser

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#4]
Learner > Choose a Compatible Web Browser (Suggestion)

Consider adding the directive that the user can type “Chrome” or “Edge” into the search function on their desktop. Not an issue, but I have had to give this directive on calls before. Pic below:

![image](https://user-images.githubusercontent.com/73358235/118867305-2af66100-b8a0-11eb-8871-1b07f554195b.png)

**Comment by artlessdodger** [comment]
Patched in the next release. Images for the search menu have been added with instructions.

See commit [f258df6 ](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/f258df6030c4130316ac3899a2566c9d410f6079)for details.
