### ISSUE TITLE
Learner | Use Tab Functionality

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#5]
Learner | Use Tab Functionality (Suggestion)

Consider using a larger photo of multiple tabs for better readability (including multiple tabs, URL Activity Tab, and Social Board Tab photos at the top and middle of this page. 

Consider using light mode for these photos as well (image 1 below)

Consider using the visual of the keyboard with highlighted CTRL+Tab or CTRL+1 (visual of keyboard for reference located in Learner | Clear a Browser’s Cache, image 2 below)

![image](https://user-images.githubusercontent.com/73358235/118867781-af48e400-b8a0-11eb-922b-e5165f49bfba.png)

![image](https://user-images.githubusercontent.com/73358235/118867907-d56e8400-b8a0-11eb-9c8c-f5e1e234e8fd.png)

**Comment by artlessdodger** [comment]
Patched in the next release. Images for browser tabs now contain dark and light mode and are larger. Keyboard images with highlights have been added. 

See commit [f258df6](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/f258df6030c4130316ac3899a2566c9d410f6079) for details.
