### ISSUE TITLE
Instructor | Accept and Reject File Submissions

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#6]
Instructor | Accept and Reject File Submissions (Suggestion)

Consider providing reason(s) why one might reject a file submission, such as if a student were to inform the instructor that they uploaded the wrong file, or hadn't combined their pdfs prior to submission.

**Comment by artlessdodger** [comment]
Patched in the next release. Reasoning has been added to the introduction section element.

See commit [e3fo3a5](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/e3f03a53128b10f38401b02bf32f6f43744d1009) for details.
