### ISSUE TITLE
Concurrence Reviewer | Conduct a Concurrence Review

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#7]
Concurrence Reviewer | Conduct a concurrence review (Suggestion)

Consider noting that comments should include references (M21, eCFR, court cases, etc.) when applicable.

**Comment by artlessdodger** [comment]
Patched in the next release. The note requesting that comments be limited to content has been expanded to request legal, regulatory, or procedural references where applicable.

See commit [6636ef8](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/6636ef824f6cdf1a7ceb98fce4fd91343283748c) for details.
