### ISSUE TITLE
Administrator | Add a User or User Role

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#8]
Administrator | Add a User or User Role (Suggestion)

When creating a new account for a user, they do not need to fill in the manager role, it will automatically populate Jeff Pearson. Consider making a note that Admins do not need to write Jeff Pearson for each account they create.

**Comment by artlessdodger** [comment]
Patched in the next release. The note indicating fillable form values has been expanded to include this information.

See commit [6636ef8](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/6636ef824f6cdf1a7ceb98fce4fd91343283748c) for details.
