### ISSUE TITLE
Administrator | Edit Existing Account  

### ISSUE THREAD

**Issue by LJCarey** [compensationServiceTraining/primeTechnicalManual#9]
Administrator | Edit Existing Account (Suggestion)

Suggestion: Adding instructions on updating an existing account due to name/email change. 

When users change their names and VA email addresses, you may edit their existing account instead of creating a new account. You can also update the Station ID number under Profile if a user moves to another station. 

From the Internal User screen, look up the employee by name or email address. 

![image](https://user-images.githubusercontent.com/73358235/118869509-b4a72e00-b8a2-11eb-8c5a-33698ca0a3e6.png)

Select the pencil at the top right of the highlighted box. 

![image](https://user-images.githubusercontent.com/73358235/118869635-ddc7be80-b8a2-11eb-93b2-054edb6f5f54.png)

Update the user's name, email address, and Adobe ID, then select Save. 

![image](https://user-images.githubusercontent.com/73358235/118869949-4020bf00-b8a3-11eb-9d15-4880023c9764.png)

Now you should see the updated name and email address. 

![image](https://user-images.githubusercontent.com/73358235/118870066-63e40500-b8a3-11eb-9b81-32765bc67e12.png)

**Comment by artlessdodger** [comment]
Patched in the next release. A subpage has been created to address this task.

See commit [2fe3b3c](https://github.com/compensationServiceTraining/primeTechnicalManual/commit/2fe3b3c42920419ddc4dce08bd29d3badea3f453) for details.
